import type { Metadata } from "next";
import "./globals.css";
import {PropsWithChildren} from "react";
import {Poppins} from "next/font/google";

export const metadata: Metadata = {
  title: "A Software Development Agency | PROSOLAB",
  description: "Generated by create next app",
};

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});


export default function RootLayout({children}: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  );
}
